### ISSUE TITLE
Cannot run "build" command

### ISSUE THREAD

**Issue by emanueletortolone** [fabiocaccamo/utils.js#2]
Hi! 👋
If I try to run `npm run build` the CMD returns these error:
```
Failed to load external module @babel/register
   ...  
Error in plugin 'gulp-js-import'
Message:
    file ./utils/ArrayUtil.js no exist
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

I followed your development guides, upgraded all the tools (gulp, npm, node) but the build process did not worked.
Do you have any tips to solve this issue? 
Thank you 😊

**Comment by fabiocaccamo** [comment]
This problem seems to be related to how `gulp-js-import` handle paths.

Unfortunately I can't reproduce the problem, could you try to remove the `./` prefix from all `@import` in `utils.js` and retry?

**Comment by emanueletortolone** [comment]
So, I cloned the repo from scratch, and run `npm install`.
First strange thing is that `gulp` is not installed locally (maybe the package was not added to `package.json` or maybe you have `gulp` globally installed.
Installing `gulp` I'm able to build the scripts, but unfortunatly there is an error in `minify` task:
```
[14:38:39] TypeError in plugin "gulp-minify"
Message:
    src\utils.js
Cannot read property 'replace' of undefined (line: undefined, col: undefined, pos: undefined
```
If I simply comment the `gulp-minify` pipeline, then the build task passes (I did not modified the `@import` path on utils.js).
¯\_(ツ)_/¯

**Comment by fabiocaccamo** [comment]
It's really strange, as you can see in [package.json](https://github.com/fabiocaccamo/utils.js/blob/master/package.json#L47), there is the gulp dependency.

The `gulp-minify` problem, could be related to es5 code, could you try to install     `gulp-minify 0.0.15` version?

**Comment by emanueletortolone** [comment]
@fabiocaccamo 
1. I installed  `gulp-minify@0.0.15` but problem still persist ... `¯\_(ツ)_/¯`
```
[20:49:33] 'javascript' errored after 210 ms
[20:49:33] SyntaxError in plugin 'gulp-minify'
```
2. Now when I try run `npm run test` it does not recognize `nyc` before `mocha`: maybe did you missed some references? 😞

**Comment by fabiocaccamo** [comment]
@emanueletortolone I updated all `devDependencies` in `package.json`, could you try to re-install all `node_modules` and let me know if the problem persists?

**Comment by fabiocaccamo** [comment]
@emanueletortolone I close this due to inactivity, feel free to re-open it if you have any update.
